### ISSUE TITLE
feat: Directly input the symbol instead of copying it

### ISSUE THREAD

**Issue by PRO-2684** [nathancartlidge/powertoys-run-agda#2]
I suggest that the default behavior should be inputting the selected symbol at current cursor position instead of copying it to the clipboard. To be precise, when a symbol is selected:

- Pressing `Enter` inputs it
- Pressing `Ctrl+C` copies it to clipboard

[Input Typer](https://github.com/CoreyHayward/PowerToys-Run-InputTyper) might be of some help regarding how to simulate user input.

**Comment by nathancartlidge** [comment]
That would be great feature to have, thanks for the feeback!

I'd looked into implementing Input Typer's functionality in the past and for some reason came to the incorrect conclusion that it didn't properly support unicode characters - I just checked and this doesn't seem to actually be the case!

Unfortunately I'm not sure I can detect Ctrl+C presses in the run window, so that'd have to be a clickable button instead - I'll play around with dififerent combinations and see what works best :)

**Comment by PRO-2684** [comment]
> Unfortunately I'm not sure I can detect Ctrl+C presses in the run window, so that'd have to be a clickable button instead - I'll play around with dififerent combinations and see what works best :)

The built-in [`Windows settings`](https://github.com/microsoft/PowerToys/tree/2ea9d5612906ec7aba638bc7c72469751c725f0d/src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings) plugin does have this feature of using `Ctrl+C` to copy respective command:

![image](https://github.com/user-attachments/assets/1ddcbee2-730d-4c84-a16d-1312c5c7efe1)

Hope it helps :)

**Comment by nathancartlidge** [comment]
My mistake! Thank you for pointing that out, turns out that's a feature of `ContextMenuResult` I was completely unaware of :)
